development:
  cloud_name: zombie-apocalypse-survival
  api_key: '768493731668994'
  api_secret: "49NY7eEWuG6N2Zng1CesPE2xxOE"
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: zombie-apocalypse-survival
  api_key: '768493731668994'
  api_secret: "49NY7eEWuG6N2Zng1CesPE2xxOE"
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: zombie-apocalypse-survival
  api_key: '768493731668994'
  api_secret: "49NY7eEWuG6N2Zng1CesPE2xxOE"
  enhance_image_tag: true
  static_file_support: false