# PostgreSQL. Versions 1.2.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
#
# Configure Using Gemfile
# gem 'pg'
#
development:
  adapter: postgresql
  database: zombie_apocalypse_survival_development
  username: admin
  password: admin
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: zombie_apocalypse_survival_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: zombie_apocalypse_survival_production
  pool: 5
  timeout: 5000